# Generated by Django 4.1.3 on 2022-11-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspaper",
            name="content",
            field=models.TextField(default="Some content2"),
        ),
    ]
